"""Several businesses in one app and one PostgreSQL database, each in its own schema.

The directory (schema `nirkana_operador`) lists the businesses: their code (used in the address, `?negocio=code`),
name, status and the one-time setup code that lets the business create its first administrator. Each business's
data lives in schema `n_<code>`, created with the same tables as a single-business database, so nothing a business
does can read or change another's data: every query runs with its own schema as the search path.
"""

import re
import secrets
from datetime import datetime, timedelta

from . import clock
from .billing import TRIAL_DAYS, subscription_fields, utc_now
from .db import Store, _secure_url
from .security import hash_secret, verify_secret

DIRECTORY_SCHEMA = "nirkana_operador"
CODE_RE = re.compile(r"[a-z0-9](?:[a-z0-9-]{1,38}[a-z0-9])")
STATUSES = {"activo": "Activo", "suspendido": "Suspendido"}
TENANT_FIELDS = ("code, name, schema_name, status, contact, created_at, setup_used_at, billing_status, trial_ends, "
                 "period_end, cancel_at_period_end, stripe_customer, stripe_subscription, billing_exempt, "
                 "billing_synced_at")
RESERVED = {"operador", "admin", "www", "app", "api", "nirkana"}

DIRECTORY_SQL = f"""
CREATE SCHEMA IF NOT EXISTS {DIRECTORY_SCHEMA};
CREATE TABLE IF NOT EXISTS {DIRECTORY_SCHEMA}.tenants (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    schema_name TEXT UNIQUE NOT NULL,
    status TEXT NOT NULL DEFAULT 'activo',
    contact TEXT NOT NULL DEFAULT '',
    setup_hash TEXT NOT NULL DEFAULT '',
    setup_used_at TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
);
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS billing_status TEXT NOT NULL DEFAULT 'prueba';
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS trial_ends TEXT NOT NULL DEFAULT '';
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS period_end TEXT NOT NULL DEFAULT '';
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS cancel_at_period_end INTEGER NOT NULL DEFAULT 0;
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS stripe_customer TEXT NOT NULL DEFAULT '';
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS stripe_subscription TEXT NOT NULL DEFAULT '';
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS billing_exempt INTEGER NOT NULL DEFAULT 0;
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS billing_synced_at TEXT NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS {DIRECTORY_SCHEMA}.stripe_events (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    received_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS {DIRECTORY_SCHEMA}.operator_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    happened_at TEXT NOT NULL,
    action TEXT NOT NULL,
    detail TEXT NOT NULL DEFAULT ''
)
"""


def normalize_code(value: str) -> str:
    return str(value or "").strip().lower()


def schema_for(code: str) -> str:
    return "n_" + code.replace("-", "_")


class Directory:
    """The list of businesses served by one database. Only the operator creates, suspends or lists them."""

    def __init__(self, url: str):
        import psycopg
        from psycopg.rows import dict_row

        self._url = _secure_url(url)
        self._connect = lambda: psycopg.connect(self._url, row_factory=dict_row, connect_timeout=15,
                                                prepare_threshold=None)
        with self._connect() as conn:
            for statement in filter(str.strip, DIRECTORY_SQL.split(";")):
                conn.execute(statement)
            # Businesses from before billing: their free trial starts the day billing arrives, not at their sign-up.
            conn.execute(f"UPDATE {DIRECTORY_SCHEMA}.tenants SET trial_ends = %s WHERE trial_ends = ''",
                         ((utc_now() + timedelta(days=TRIAL_DAYS)).isoformat(timespec="seconds"),))

    def _log(self, conn, action: str, detail: str = "") -> None:
        conn.execute(f"INSERT INTO {DIRECTORY_SCHEMA}.operator_log(happened_at, action, detail) VALUES (%s, %s, %s)",
                     (clock.now().isoformat(timespec="seconds"), action, detail[:300]))

    # ------------------------------------------------------------------ businesses
    def get(self, code: str) -> dict | None:
        code = normalize_code(code)
        if not CODE_RE.fullmatch(code):
            return None
        with self._connect() as conn:
            return conn.execute(f"SELECT {TENANT_FIELDS} FROM {DIRECTORY_SCHEMA}.tenants WHERE code = %s",
                                (code,)).fetchone()

    def create(self, code: str, name: str, contact: str = "", trial_days: int = TRIAL_DAYS) -> str:
        """Create a business with its own schema and tables. Returns its one-time setup code (shown only once)."""
        code = normalize_code(code)
        if not CODE_RE.fullmatch(code) or "--" in code:
            raise ValueError("El código debe tener de 3 a 40 letras minúsculas, números o guiones (p. ej. cafe-aurora).")
        if code in RESERVED:
            raise ValueError("Ese código está reservado. Elige otro.")
        name = str(name or "").strip()[:120]
        if not name:
            raise ValueError("Escribe el nombre del negocio.")
        if self.get(code):
            raise ValueError("Ya existe un negocio con ese código.")
        schema = schema_for(code)
        setup = secrets.token_hex(4).upper()
        with self._connect() as conn:
            conn.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
        store = Store(self._url, schema=schema)  # creates every table of a business in its schema
        try:
            store.save_settings({"business_name": name})
        finally:
            store.close()
        with self._connect() as conn:
            trial_ends = (utc_now() + timedelta(days=int(trial_days))).isoformat(timespec="seconds")
            conn.execute(f"INSERT INTO {DIRECTORY_SCHEMA}.tenants(code, name, schema_name, contact, setup_hash, "
                         "created_at, trial_ends) VALUES (%s, %s, %s, %s, %s, %s, %s)",
                         (code, name, schema, str(contact or "")[:200], hash_secret(setup),
                          clock.now().isoformat(timespec="seconds"), trial_ends))
            self._log(conn, "negocio_creado", f"{code} · {name}")
        return setup

    def check_setup_code(self, code: str, setup: str) -> bool:
        """The business's one-time code for creating its first administrator."""
        with self._connect() as conn:
            row = conn.execute(f"SELECT setup_hash, setup_used_at FROM {DIRECTORY_SCHEMA}.tenants WHERE code = %s",
                               (normalize_code(code),)).fetchone()
        return bool(row and row["setup_hash"] and not row["setup_used_at"]
                    and verify_secret(str(setup or "").strip().upper(), row["setup_hash"]))

    def mark_setup_used(self, code: str) -> None:
        with self._connect() as conn:
            conn.execute(f"UPDATE {DIRECTORY_SCHEMA}.tenants SET setup_used_at = %s WHERE code = %s",
                         (clock.now().isoformat(timespec="seconds"), normalize_code(code)))
            self._log(conn, "administrador_creado", normalize_code(code))

    def new_setup_code(self, code: str) -> str:
        """A fresh one-time code, e.g. when the business lost it before creating its administrator."""
        setup = secrets.token_hex(4).upper()
        with self._connect() as conn:
            updated = conn.execute(f"UPDATE {DIRECTORY_SCHEMA}.tenants SET setup_hash = %s, setup_used_at = '' "
                                   "WHERE code = %s", (hash_secret(setup), normalize_code(code))).rowcount
            if not updated:
                raise ValueError("Negocio no encontrado.")
            self._log(conn, "codigo_instalacion_nuevo", normalize_code(code))
        return setup

    def set_status(self, code: str, status: str) -> None:
        if status not in STATUSES:
            raise ValueError("Estado no válido.")
        with self._connect() as conn:
            updated = conn.execute(f"UPDATE {DIRECTORY_SCHEMA}.tenants SET status = %s WHERE code = %s",
                                   (status, normalize_code(code))).rowcount
            if not updated:
                raise ValueError("Negocio no encontrado.")
            self._log(conn, f"negocio_{status}", normalize_code(code))

    def overview(self) -> list[dict]:
        """Every business with its activity, for the operator panel."""
        with self._connect() as conn:
            tenants = conn.execute(f"SELECT {TENANT_FIELDS} FROM {DIRECTORY_SCHEMA}.tenants "
                                   "ORDER BY created_at").fetchall()
            for t in tenants:
                schema = t["schema_name"]
                stats = conn.execute(
                    f'SELECT COUNT(*) AS sales, MAX(created_at) AS last_sale FROM "{schema}".sales').fetchone()
                users = conn.execute(f'SELECT COUNT(*) AS n FROM "{schema}".users WHERE active = 1').fetchone()
                errors = 0
                if conn.execute("SELECT to_regclass(%s) AS t", (f"{schema}.app_errors",)).fetchone()["t"]:
                    since = (clock.now() - timedelta(days=7)).isoformat(timespec="seconds")
                    errors = conn.execute(f'SELECT COUNT(*) AS n FROM "{schema}".app_errors WHERE happened_at >= %s',
                                          (since,)).fetchone()["n"]
                t.update(sales=stats["sales"], last_sale=stats["last_sale"] or "", users=users["n"], errors=errors)
        return tenants

    # ------------------------------------------------------------------ billing
    def _billing_update(self, conn, code: str, fields: dict, action: str) -> bool:
        allowed = {"billing_status", "trial_ends", "period_end", "cancel_at_period_end", "stripe_customer",
                   "stripe_subscription", "billing_exempt"}
        fields = {k: v for k, v in fields.items() if k in allowed}
        fields["billing_synced_at"] = utc_now().isoformat(timespec="seconds")
        sets = ", ".join(f"{k} = %s" for k in fields)
        updated = conn.execute(f"UPDATE {DIRECTORY_SCHEMA}.tenants SET {sets} WHERE code = %s",
                               (*fields.values(), normalize_code(code))).rowcount
        if updated and action:
            self._log(conn, action, f"{normalize_code(code)} · {fields.get('billing_status', '')}".strip(" ·"))
        return bool(updated)

    def record_subscription(self, code: str, subscription: dict, action: str = "suscripcion_actualizada") -> bool:
        """Keep a business's subscription as Stripe reports it."""
        with self._connect() as conn:
            return self._billing_update(conn, code, subscription_fields(subscription), action)

    def set_billing_exempt(self, code: str, exempt: bool) -> None:
        """Businesses that use the service free of charge (pilots, friends): never asked to pay."""
        with self._connect() as conn:
            if not self._billing_update(conn, code, {"billing_exempt": int(bool(exempt))}, ""):
                raise ValueError("Negocio no encontrado.")
            self._log(conn, "cortesia_activada" if exempt else "cortesia_retirada", normalize_code(code))

    def extend_trial(self, code: str, days: int) -> None:
        tenant = self.get(code)
        if tenant is None:
            raise ValueError("Negocio no encontrado.")
        if not 1 <= int(days) <= 365:
            raise ValueError("Amplía entre 1 y 365 días.")
        start = max(utc_now(), datetime.fromisoformat(tenant["trial_ends"]) if tenant["trial_ends"] else utc_now())
        with self._connect() as conn:
            self._billing_update(conn, code, {"trial_ends": (start + timedelta(days=int(days))).isoformat(
                timespec="seconds")}, "")
            self._log(conn, "prueba_ampliada", f"{normalize_code(code)} · {int(days)} días")

    def tenant_for_customer(self, customer: str) -> str | None:
        with self._connect() as conn:
            row = conn.execute(f"SELECT code FROM {DIRECTORY_SCHEMA}.tenants WHERE stripe_customer = %s",
                               (customer,)).fetchone()
        return row["code"] if row else None

    def process_event(self, event: dict) -> str:
        """Apply a (signature-checked) Stripe event once. Returns what was done, for the log and tests."""
        with self._connect() as conn:
            fresh = conn.execute(f"INSERT INTO {DIRECTORY_SCHEMA}.stripe_events(id, type, received_at) "
                                 "VALUES (%s, %s, %s) ON CONFLICT (id) DO NOTHING",
                                 (event["id"], str(event.get("type", ""))[:80],
                                  utc_now().isoformat(timespec="seconds"))).rowcount
        if not fresh:
            return "repetido"
        kind = event.get("type", "")
        obj = (event.get("data") or {}).get("object") or {}
        if kind == "checkout.session.completed":
            code = obj.get("client_reference_id") or (obj.get("metadata") or {}).get("tenant")
            if not code or not self.get(code):
                return "ignorado"
            subscription = obj.get("subscription")
            if isinstance(subscription, dict):
                self.record_subscription(code, subscription, "suscripcion_contratada")
            else:  # not expanded: link the customer now; the subscription's own event (any order) brings its state
                with self._connect() as conn:
                    self._billing_update(conn, code, {"stripe_customer": obj.get("customer") or "",
                                                      "stripe_subscription": subscription or ""},
                                         "suscripcion_contratada")
            return "vinculado"
        if kind.startswith("customer.subscription."):
            code = (obj.get("metadata") or {}).get("tenant") or self.tenant_for_customer(
                obj["customer"]["id"] if isinstance(obj.get("customer"), dict) else obj.get("customer") or "")
            tenant = self.get(code) if code else None
            if tenant is None:
                return "ignorado"
            if tenant["stripe_subscription"] and obj.get("id") != tenant["stripe_subscription"] \
                    and tenant["billing_status"] in ("active", "trialing") and obj.get("status") not in ("active",
                                                                                                         "trialing"):
                return "ignorado"  # an old or abandoned subscription must not override the one that is paid
            self.record_subscription(code, obj, "suscripcion_" + kind.rsplit(".", 1)[-1])
            return "actualizado"
        return "ignorado"

    def sync_subscription(self, code: str, stripe) -> dict | None:
        """Ask Stripe for a business's latest subscription (safety net for lost webhooks)."""
        tenant = self.get(code)
        if tenant is None or not tenant["stripe_customer"]:
            return tenant
        subscription = stripe.latest_subscription(tenant["stripe_customer"])
        if subscription:
            self.record_subscription(code, subscription, "")
        return self.get(code)

    def log(self, limit: int = 100) -> list[dict]:
        with self._connect() as conn:
            return conn.execute(f"SELECT happened_at, action, detail FROM {DIRECTORY_SCHEMA}.operator_log "
                                "ORDER BY id DESC LIMIT %s", (limit,)).fetchall()

    def store(self, code: str) -> Store:
        tenant = self.get(code)
        if tenant is None:
            raise ValueError("Negocio no encontrado.")
        return Store(self._url, schema=tenant["schema_name"])



def businesses_in(url: str) -> list[tuple[str, str | None]]:
    """(code, schema) of each active business served by a database; [("", None)] for a single-business one.
    Only reads: unlike Directory, it never creates the directory."""
    import psycopg
    from psycopg.rows import dict_row

    with psycopg.connect(_secure_url(url), row_factory=dict_row, connect_timeout=30) as conn:
        if not conn.execute("SELECT to_regclass(%s) AS t", (f"{DIRECTORY_SCHEMA}.tenants",)).fetchone()["t"]:
            return [("", None)]
        rows = conn.execute(f"SELECT code, schema_name FROM {DIRECTORY_SCHEMA}.tenants WHERE status = 'activo' "
                            "ORDER BY code").fetchall()
    return [(r["code"], r["schema_name"]) for r in rows]
