"""Several businesses in one app and one PostgreSQL database, each in its own schema.

The directory (schema `nirkana_operador`) lists the businesses: their code (used in the address, `?negocio=code`),
name, status and the one-time setup code that lets the business create its first administrator. Each business's
data lives in schema `n_<code>`, created with the same tables as a single-business database, so nothing a business
does can read or change another's data: every query runs with its own schema as the search path.
"""

import json
import re
import secrets
import time
from datetime import datetime, timedelta

from . import clock, logs
from .billing import TRIAL_DAYS, Access, BillingError, access, parse_when, subscription_fields, utc_now
from .db import Store
from .engines import secure_url, acquire_pool, release_pool
from .throttle import after_failure, blocked_minutes, key_hash
from .security import hash_secret, verify_secret

DIRECTORY_SCHEMA = "nirkana_operador"
log = logs.get("tenants")
CODE_RE = re.compile(r"[a-z0-9](?:[a-z0-9-]{1,38}[a-z0-9])")
STATUSES = {"activo": "Activo", "suspendido": "Suspendido"}
TENANT_FIELDS = ("code, name, schema_name, status, contact, created_at, setup_used_at, billing_status, trial_ends, "
                 "period_end, cancel_at_period_end, stripe_customer, stripe_subscription, billing_exempt, "
                 "billing_synced_at")
RESERVED = {"operador", "admin", "www", "app", "api", "nirkana"}

DIRECTORY_SQL = f"""
CREATE SCHEMA IF NOT EXISTS {DIRECTORY_SCHEMA};
CREATE TABLE IF NOT EXISTS {DIRECTORY_SCHEMA}.tenants (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    schema_name TEXT UNIQUE NOT NULL,
    status TEXT NOT NULL DEFAULT 'activo',
    contact TEXT NOT NULL DEFAULT '',
    setup_hash TEXT NOT NULL DEFAULT '',
    setup_used_at TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
);
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS billing_status TEXT NOT NULL DEFAULT 'prueba';
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS trial_ends TEXT NOT NULL DEFAULT '';
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS period_end TEXT NOT NULL DEFAULT '';
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS cancel_at_period_end INTEGER NOT NULL DEFAULT 0;
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS stripe_customer TEXT NOT NULL DEFAULT '';
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS stripe_subscription TEXT NOT NULL DEFAULT '';
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS billing_exempt INTEGER NOT NULL DEFAULT 0;
ALTER TABLE {DIRECTORY_SCHEMA}.tenants ADD COLUMN IF NOT EXISTS billing_synced_at TEXT NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS {DIRECTORY_SCHEMA}.stripe_events (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    received_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS {DIRECTORY_SCHEMA}.operator_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    happened_at TEXT NOT NULL,
    action TEXT NOT NULL,
    detail TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS {DIRECTORY_SCHEMA}.operator_totp (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    last_step BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS {DIRECTORY_SCHEMA}.login_throttle (
    key TEXT PRIMARY KEY,
    fails TEXT NOT NULL DEFAULT '[]',
    blocked_until BIGINT NOT NULL DEFAULT 0,
    level INTEGER NOT NULL DEFAULT 0,
    updated BIGINT NOT NULL DEFAULT 0
)
"""
# Billing is re-checked with Stripe this often, in case a webhook was lost.
SYNC_EVERY = timedelta(hours=6)


def normalize_code(value: str) -> str:
    return str(value or "").strip().lower()


def schema_for(code: str) -> str:
    return "n_" + code.replace("-", "_")


class Directory:
    """The list of businesses served by one database. Only the operator creates, suspends or lists them."""

    def __init__(self, url: str):
        self._url = secure_url(url)
        # The same pool as the businesses' stores on this database, instead of a new connection per call.
        self._pool_key, pool = acquire_pool(url)
        self._connect = pool.connection
        with self._connect() as conn:
            for statement in filter(str.strip, DIRECTORY_SQL.split(";")):
                conn.execute(statement)
            # Businesses from before billing: their free trial starts the day billing arrives, not at their sign-up.
            conn.execute(f"UPDATE {DIRECTORY_SCHEMA}.tenants SET trial_ends = %s WHERE trial_ends = ''",
                         ((utc_now() + timedelta(days=TRIAL_DAYS)).isoformat(timespec="seconds"),))

    def _log(self, conn, action: str, detail: str = "") -> None:
        conn.execute(f"INSERT INTO {DIRECTORY_SCHEMA}.operator_log(happened_at, action, detail) VALUES (%s, %s, %s)",
                     (clock.now().isoformat(timespec="seconds"), action, detail[:300]))

    # ------------------------------------------------------------------ businesses
    def get(self, code: str) -> dict | None:
        code = normalize_code(code)
        if not CODE_RE.fullmatch(code):
            return None
        with self._connect() as conn:
            return conn.execute(f"SELECT {TENANT_FIELDS} FROM {DIRECTORY_SCHEMA}.tenants WHERE code = %s",
                                (code,)).fetchone()

    def create(self, code: str, name: str, contact: str = "", trial_days: int = TRIAL_DAYS) -> str:
        """Create a business with its own schema and tables. Returns its one-time setup code (shown only once)."""
        code = normalize_code(code)
        if not CODE_RE.fullmatch(code) or "--" in code:
            raise ValueError("El código debe tener de 3 a 40 letras minúsculas, números o guiones (p. ej. cafe-aurora).")
        if code in RESERVED:
            raise ValueError("Ese código está reservado. Elige otro.")
        name = str(name or "").strip()[:120]
        if not name:
            raise ValueError("Escribe el nombre del negocio.")
        if self.get(code):
            raise ValueError("Ya existe un negocio con ese código.")
        schema = schema_for(code)
        setup = secrets.token_hex(4).upper()
        with self._connect() as conn:
            conn.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
        store = Store(self._url, schema=schema)  # creates every table of a business in its schema
        try:
            store.save_settings({"business_name": name})
        finally:
            store.close()
        with self._connect() as conn:
            trial_ends = (utc_now() + timedelta(days=int(trial_days))).isoformat(timespec="seconds")
            conn.execute(f"INSERT INTO {DIRECTORY_SCHEMA}.tenants(code, name, schema_name, contact, setup_hash, "
                         "created_at, trial_ends) VALUES (%s, %s, %s, %s, %s, %s, %s)",
                         (code, name, schema, str(contact or "")[:200], hash_secret(setup),
                          clock.now().isoformat(timespec="seconds"), trial_ends))
            self._log(conn, "negocio_creado", f"{code} · {name}")
        return setup

    def check_setup_code(self, code: str, setup: str) -> bool:
        """The business's one-time code for creating its first administrator."""
        with self._connect() as conn:
            row = conn.execute(f"SELECT setup_hash, setup_used_at FROM {DIRECTORY_SCHEMA}.tenants WHERE code = %s",
                               (normalize_code(code),)).fetchone()
        return bool(row and row["setup_hash"] and not row["setup_used_at"]
                    and verify_secret(str(setup or "").strip().upper(), row["setup_hash"]))

    def mark_setup_used(self, code: str) -> None:
        with self._connect() as conn:
            conn.execute(f"UPDATE {DIRECTORY_SCHEMA}.tenants SET setup_used_at = %s WHERE code = %s",
                         (clock.now().isoformat(timespec="seconds"), normalize_code(code)))
            self._log(conn, "administrador_creado", normalize_code(code))

    def new_setup_code(self, code: str) -> str:
        """A fresh one-time code, e.g. when the business lost it before creating its administrator."""
        setup = secrets.token_hex(4).upper()
        with self._connect() as conn:
            updated = conn.execute(f"UPDATE {DIRECTORY_SCHEMA}.tenants SET setup_hash = %s, setup_used_at = '' "
                                   "WHERE code = %s", (hash_secret(setup), normalize_code(code))).rowcount
            if not updated:
                raise ValueError("Negocio no encontrado.")
            self._log(conn, "codigo_instalacion_nuevo", normalize_code(code))
        return setup

    def set_status(self, code: str, status: str) -> None:
        if status not in STATUSES:
            raise ValueError("Estado no válido.")
        with self._connect() as conn:
            updated = conn.execute(f"UPDATE {DIRECTORY_SCHEMA}.tenants SET status = %s WHERE code = %s",
                                   (status, normalize_code(code))).rowcount
            if not updated:
                raise ValueError("Negocio no encontrado.")
            self._log(conn, f"negocio_{status}", normalize_code(code))

    def overview(self) -> list[dict]:
        """Every business with its activity, for the operator panel."""
        with self._connect() as conn:
            tenants = conn.execute(f"SELECT {TENANT_FIELDS} FROM {DIRECTORY_SCHEMA}.tenants "
                                   "ORDER BY created_at").fetchall()
            for t in tenants:
                schema = t["schema_name"]
                stats = conn.execute(
                    f'SELECT COUNT(*) AS sales, MAX(created_at) AS last_sale FROM "{schema}".sales').fetchone()
                users = conn.execute(f'SELECT COUNT(*) AS n FROM "{schema}".users WHERE active = 1').fetchone()
                errors = 0
                if conn.execute("SELECT to_regclass(%s) AS t", (f"{schema}.app_errors",)).fetchone()["t"]:
                    since = (clock.now() - timedelta(days=7)).isoformat(timespec="seconds")
                    errors = conn.execute(f'SELECT COUNT(*) AS n FROM "{schema}".app_errors WHERE happened_at >= %s',
                                          (since,)).fetchone()["n"]
                t.update(sales=stats["sales"], last_sale=stats["last_sale"] or "", users=users["n"], errors=errors)
        return tenants

    # ------------------------------------------------------------------ billing
    def _billing_update(self, conn, code: str, fields: dict, action: str) -> bool:
        allowed = {"billing_status", "trial_ends", "period_end", "cancel_at_period_end", "stripe_customer",
                   "stripe_subscription", "billing_exempt"}
        fields = {k: v for k, v in fields.items() if k in allowed}
        fields["billing_synced_at"] = utc_now().isoformat(timespec="seconds")
        sets = ", ".join(f"{k} = %s" for k in fields)
        updated = conn.execute(f"UPDATE {DIRECTORY_SCHEMA}.tenants SET {sets} WHERE code = %s",
                               (*fields.values(), normalize_code(code))).rowcount
        if updated and action:
            self._log(conn, action, f"{normalize_code(code)} · {fields.get('billing_status', '')}".strip(" ·"))
        return bool(updated)

    def record_subscription(self, code: str, subscription: dict, action: str = "suscripcion_actualizada") -> bool:
        """Keep a business's subscription as Stripe reports it."""
        with self._connect() as conn:
            return self._billing_update(conn, code, subscription_fields(subscription), action)

    def set_billing_exempt(self, code: str, exempt: bool) -> None:
        """Businesses that use the service free of charge (pilots, friends): never asked to pay."""
        with self._connect() as conn:
            if not self._billing_update(conn, code, {"billing_exempt": int(bool(exempt))}, ""):
                raise ValueError("Negocio no encontrado.")
            self._log(conn, "cortesia_activada" if exempt else "cortesia_retirada", normalize_code(code))

    def extend_trial(self, code: str, days: int) -> None:
        tenant = self.get(code)
        if tenant is None:
            raise ValueError("Negocio no encontrado.")
        if not 1 <= int(days) <= 365:
            raise ValueError("Amplía entre 1 y 365 días.")
        start = max(utc_now(), datetime.fromisoformat(tenant["trial_ends"]) if tenant["trial_ends"] else utc_now())
        with self._connect() as conn:
            self._billing_update(conn, code, {"trial_ends": (start + timedelta(days=int(days))).isoformat(
                timespec="seconds")}, "")
            self._log(conn, "prueba_ampliada", f"{normalize_code(code)} · {int(days)} días")

    def tenant_for_customer(self, customer: str) -> str | None:
        with self._connect() as conn:
            row = conn.execute(f"SELECT code FROM {DIRECTORY_SCHEMA}.tenants WHERE stripe_customer = %s",
                               (customer,)).fetchone()
        return row["code"] if row else None

    def process_event(self, event: dict) -> str:
        """Apply a (signature-checked) Stripe event once. Returns what was done, for the log and tests."""
        with self._connect() as conn:
            fresh = conn.execute(f"INSERT INTO {DIRECTORY_SCHEMA}.stripe_events(id, type, received_at) "
                                 "VALUES (%s, %s, %s) ON CONFLICT (id) DO NOTHING",
                                 (event["id"], str(event.get("type", ""))[:80],
                                  utc_now().isoformat(timespec="seconds"))).rowcount
        if not fresh:
            return "repetido"
        kind = event.get("type", "")
        obj = (event.get("data") or {}).get("object") or {}
        if kind == "checkout.session.completed":
            code = obj.get("client_reference_id") or (obj.get("metadata") or {}).get("tenant")
            if not code or not self.get(code):
                return "ignorado"
            subscription = obj.get("subscription")
            if isinstance(subscription, dict):
                self.record_subscription(code, subscription, "suscripcion_contratada")
            else:  # not expanded: link the customer now; the subscription's own event (any order) brings its state
                with self._connect() as conn:
                    self._billing_update(conn, code, {"stripe_customer": obj.get("customer") or "",
                                                      "stripe_subscription": subscription or ""},
                                         "suscripcion_contratada")
            return "vinculado"
        if kind.startswith("customer.subscription."):
            code = (obj.get("metadata") or {}).get("tenant") or self.tenant_for_customer(
                obj["customer"]["id"] if isinstance(obj.get("customer"), dict) else obj.get("customer") or "")
            tenant = self.get(code) if code else None
            if tenant is None:
                return "ignorado"
            if tenant["stripe_subscription"] and obj.get("id") != tenant["stripe_subscription"] \
                    and tenant["billing_status"] in ("active", "trialing") and obj.get("status") not in ("active",
                                                                                                         "trialing"):
                return "ignorado"  # an old or abandoned subscription must not override the one that is paid
            self.record_subscription(code, obj, "suscripcion_" + kind.rsplit(".", 1)[-1])
            return "actualizado"
        return "ignorado"

    def sync_subscription(self, code: str, stripe) -> dict | None:
        """Ask Stripe for a business's latest subscription (safety net for lost webhooks)."""
        tenant = self.get(code)
        if tenant is None or not tenant["stripe_customer"]:
            return tenant
        subscription = stripe.latest_subscription(tenant["stripe_customer"])
        if subscription:
            self.record_subscription(code, subscription, "")
        return self.get(code)

    def log(self, limit: int = 100) -> list[dict]:
        with self._connect() as conn:
            return conn.execute(f"SELECT happened_at, action, detail FROM {DIRECTORY_SCHEMA}.operator_log "
                                "ORDER BY id DESC LIMIT %s", (limit,)).fetchall()

    def close(self) -> None:
        release_pool(self._pool_key)

    # ------------------------------------------------------------- billing access
    def access_for(self, tenant: dict, stripe, checkout_session_id: str = "") -> tuple[Access, str, bool]:
        """What a business may do now, and a message for its visitor (or ""). Records a subscription just bought
        (`checkout_session_id`, when returning from Stripe Checkout) and re-checks with Stripe every SYNC_EVERY in
        case a webhook was lost. Full access while billing is off (`stripe` is None). The last value tells whether the
        directory was asked again (so cached copies of the business are stale)."""
        if stripe is None:
            return Access("full"), "", False
        message, refreshed = "", False
        if checkout_session_id:
            try:
                session = stripe.checkout_session(checkout_session_id)
                if session.get("client_reference_id") == tenant["code"] and isinstance(session.get("subscription"),
                                                                                       dict):
                    self.record_subscription(tenant["code"], session["subscription"], "suscripcion_contratada")
                    message = "¡Gracias! Tu suscripción está activa."
            except BillingError as exc:
                message = str(exc)
            tenant = self.get(tenant["code"]) or tenant
            refreshed = True
        synced = parse_when(tenant.get("billing_synced_at"))
        if tenant.get("stripe_customer") and (synced is None or utc_now() - synced > SYNC_EVERY):
            try:
                tenant = self.sync_subscription(tenant["code"], stripe) or tenant
                refreshed = True
            except BillingError:
                # Stripe unreachable: keep what we know and try again on a later visit (logged by billing).
                pass
        return access(tenant, utc_now()), message, refreshed

    def claim_operator_step(self, step: int) -> bool:
        """Accept an operator two-step code of time step `step` only if no later or equal one was accepted before,
        on any server and across restarts: the same code never opens the panel twice."""
        with self._connect() as conn:
            row = conn.execute(f"INSERT INTO {DIRECTORY_SCHEMA}.operator_totp(id, last_step) VALUES (1, %s) "
                               f"ON CONFLICT (id) DO UPDATE SET last_step = excluded.last_step "
                               f"WHERE {DIRECTORY_SCHEMA}.operator_totp.last_step < excluded.last_step RETURNING id",
                               (int(step),)).fetchone()
        return row is not None

    # ------------------------------------------------- operator sign-in throttle
    # The same policy as the businesses' sign-in (core/throttle.py), kept in the directory.
    def throttle_blocked_minutes(self, key: str, now: float | None = None) -> int:
        now = time.time() if now is None else now
        with self._connect() as conn:
            row = conn.execute(f"SELECT blocked_until FROM {DIRECTORY_SCHEMA}.login_throttle WHERE key = %s",
                               (key_hash(key),)).fetchone()
        return blocked_minutes(int(row["blocked_until"]), now) if row else 0

    def throttle_failed(self, key: str, now: float | None = None) -> None:
        now = time.time() if now is None else now
        hashed = key_hash(key)
        with self._connect() as conn:
            row = conn.execute(f"SELECT fails, blocked_until, level FROM {DIRECTORY_SCHEMA}.login_throttle "
                               "WHERE key = %s FOR UPDATE", (hashed,)).fetchone()
            fails, until, level = (json.loads(row["fails"]), row["blocked_until"], row["level"]) if row else ([], 0, 0)
            fails, until, level = after_failure(fails, until, level, now)
            if until > now and not fails:
                log.warning("operator_sign_in_blocked key=%s minutes=%s", hashed[:12], blocked_minutes(until, now))
            conn.execute(f"INSERT INTO {DIRECTORY_SCHEMA}.login_throttle(key, fails, blocked_until, level, updated) "
                         "VALUES (%s, %s, %s, %s, %s) ON CONFLICT (key) DO UPDATE SET fails = excluded.fails, "
                         "blocked_until = excluded.blocked_until, level = excluded.level, updated = excluded.updated",
                         (hashed, json.dumps([int(t) for t in fails]), int(until), level, int(now)))

    def throttle_succeeded(self, key: str) -> None:
        with self._connect() as conn:
            conn.execute(f"DELETE FROM {DIRECTORY_SCHEMA}.login_throttle WHERE key = %s", (key_hash(key),))

    def store(self, code: str) -> Store:
        tenant = self.get(code)
        if tenant is None:
            raise ValueError("Negocio no encontrado.")
        return Store(self._url, schema=tenant["schema_name"])



def businesses_in(url: str) -> list[tuple[str, str | None]]:
    """(code, schema) of each active business served by a database; [("", None)] for a single-business one.
    Only reads: unlike Directory, it never creates the directory."""
    import psycopg
    from psycopg.rows import dict_row

    with psycopg.connect(secure_url(url), row_factory=dict_row, connect_timeout=30) as conn:
        if not conn.execute("SELECT to_regclass(%s) AS t", (f"{DIRECTORY_SCHEMA}.tenants",)).fetchone()["t"]:
            return [("", None)]
        rows = conn.execute(f"SELECT code, schema_name FROM {DIRECTORY_SCHEMA}.tenants WHERE status = 'activo' "
                            "ORDER BY code").fetchall()
    return [(r["code"], r["schema_name"]) for r in rows]


def migrate_all(url: str) -> list[tuple[str, int]]:
    """Bring every business on a database up to this version's schema, before the app serves anyone: a change
    then fails at deploy time, in the log, instead of on some business's first visit. Returns (code, version)."""
    done = []
    for code, schema in businesses_in(url):
        store = Store(url, schema=schema)  # sets up or migrates the schema; a no-op when it is current
        try:
            done.append((code, store.schema_version()))
        finally:
            store.close()
    return done
